const condicoesTraduzidasComEmoji = {
    Thunderstorm: "⛈️ Trovoadas",
    Drizzle: "🌦️ Garoa",
    Rain: "🌧️ Chuva",
    Snow: "❄️ Neve",
    Mist: "🌫️ Névoa",
    Smoke: "🚬 Fumaça",
    Haze: "🌫️ Neblina",
    Dust: "🌪️ Poeira",
    Fog: "🌁 Nevoeiro",
    Sand: "🏜️ Areia",
    Ash: "🌋 Cinzas",
    Squall: "🌬️ Rajada",
    Tornado: "🌪️ Tornado",
    Clear: "☀️ Céu limpo",
    Clouds: "☁️ Nuvens"
  };

  let mapa = null;
  let marcador = null; // marcador global para não duplicar

  const paisInput = document.getElementById("pais");

paisInput.addEventListener("input", function () {
  const selectedCountry = this.value;

  // Verifica se o país está no mapa e obtém a capital
  if (selectedCountry && countryCityMap[selectedCountry]) {
    const capitalCity = countryCityMap[selectedCountry];
    alert(`A capital de ${selectedCountry} é ${capitalCity}`);
  }
});

const capitaisPorPais = {
  "Afeganistão": "Cabul",
  "Albânia": "Tirana",
  "Argélia": "Argel",
  "Samoa Americana": "Pago Pago",
  "Andorra": "Andorra la Vella",
  "Angola": "Luanda",
  "Anguila": "The Valley",
  "Antártica": "N/A", // Não tem capital
  "Antígua e Barbuda": "Saint John's",
  "Argentina": "Buenos Aires",
  "Armênia": "Erevã",
  "Aruba": "Oranjestad",
  "Austrália": "Canberra",
  "Áustria": "Viena",
  "Azerbaijão": "Baku",
  "Bahamas": "Nassau",
  "Bahrein": "Manama",
  "Bangladesh": "Daca",
  "Barbados": "Bridgetown",
  "Bielorrússia": "Minsk",
  "Bélgica": "Bruxelas",
  "Belize": "Belmopan",
  "Benin": "Porto-Novo",
  "Bermudas": "Hamilton",
  "Butão": "Thimphu",
  "Bolívia": "Sucre",
  "Bonaire, Santo Eustáquio e Saba": "Kralendijk",
  "Bósnia e Herzegovina": "Sarajevo",
  "Botsuana": "Gaborone",
  "Ilha Bouvet": "N/A",
  "Brasil": "Brasília",
  "Território Britânico do Oceano Índico": "N/A",
  "Brunei": "Bandar Seri Begawan",
  "Bulgária": "Sófia",
  "Burquina Faso": "Ouagadougou",
  "Burundi": "Bujumbura",
  "Camboja": "Phnom Penh",
  "Camarões": "Yaoundé",
  "Canadá": "Ottawa",
  "Cabo Verde": "Praia",
  "Ilhas Cayman": "George Town",
  "República Centro-Africana": "Bangui",
  "Chade": "N'Djamena",
  "Chile": "Santiago",
  "China": "Pequim",
  "Ilha Christmas": "Flying Fish Cove",
  "Ilhas Cocos (Keeling)": "West Island",
  "Colômbia": "Bogotá",
  "Comores": "Moroni",
  "Coreia do Sul": "Seul",
  "Coreia do Norte": "Pyongyang",
  "Congo": "Brazzaville",
  "Congo (República Democrática do)": "Kinshasa",
  "Ilhas Cook": "Avarua",
  "Costa Rica": "San José",
  "Costa do Marfim": "Yamoussoukro",
  "Croácia": "Zagreb",
  "Cuba": "Havana",
  "Curaçao": "Willemstad",
  "Chipre": "Nicósia",
  "República Tcheca": "Praga",
  "Dinamarca": "Copenhague",
  "Djibuti": "Djibuti",
  "Dominica": "Roseau",
  "República Dominicana": "Santo Domingo",
  "Equador": "Quito",
  "Egito": "Cairo",
  "El Salvador": "San Salvador",
  "Guiné Equatorial": "Malabo",
  "Eritreia": "Asmara",
  "Estônia": "Tallinn",
  "Etiópia": "Adis Abeba",
  "Ilhas Malvinas": "Stanley",
  "Ilhas Faroe": "Tórshavn",
  "Fiji": "Suva",
  "Finlândia": "Helsinque",
  "França": "Paris",
  "Guiana Francesa": "Caiena",
  "Polinésia Francesa": "Papeete",
  "Portugal": "Lisboa",
  "Territórios Franceses do Sul": "Port-aux-Français",
  "Gabão": "Libreville",
  "Gâmbia": "Banjul",
  "Geórgia": "Tbilisi",
  "Alemanha": "Berlim",
  "Gana": "Acra",
  "Gibraltar": "Gibraltar",
  "Grécia": "Atenas",
  "Groenlândia": "Nuuk",
  "Granada": "St. George's",
  "Guadalupe": "Basse-Terre",
  "Guam": "Hagåtña",
  "Guatemala": "Cidade da Guatemala",
  "Guernsey": "St. Peter Port",
  "Guiné": "Conacri",
  "Guiné-Bissau": "Bissau",
  "Guiana": "Georgetown",
  "Haiti": "Porto Príncipe",
  "Havaí": "Honolulu",
  "Ilhas Heard e McDonald": "N/A",
  "Vaticano": "Cidade do Vaticano",
  "Honduras": "Tegucigalpa",
  "Hong Kong": "Hong Kong",
  "Hungria": "Budapeste",
  "Islândia": "Reiquiavique",
  "Índia": "Nova Délhi",
  "Indonésia": "Jacarta",
  "Irã": "Teerã",
  "Iraque": "Bagdá",
  "Irlanda": "Dublin",
  "Ilha de Man": "Douglas",
  "Israel": "Jerusalém",
  "Itália": "Roma",
  "Jamaica": "Kingston",
  "Japão": "Tóquio",
  "Jersey": "Saint Helier",
  "Jordânia": "Amã"
};

const codigosPais = {
    "Afeganistão": "AF",
    "Albânia": "AL",
    "Argélia": "DZ",
    "Samoa Americana": "AS",
    "Andorra": "AD",
    "Angola": "AO",
    "Anguila": "AI",
    "Antártica": "AQ",
    "Antígua e Barbuda": "AG",
    "Argentina": "AR",
    "Armênia": "AM",
    "Aruba": "AW",
    "Austrália": "AU",
    "Áustria": "AT",
    "Azerbaijão": "AZ",
    "Bahamas": "BS",
    "Bahrein": "BH",
    "Bangladesh": "BD",
    "Barbados": "BB",
    "Bielorrússia": "BY",
    "Bélgica": "BE",
    "Belize": "BZ",
    "Benin": "BJ",
    "Bermudas": "BM",
    "Butão": "BT",
    "Bolívia": "BO",
    "Bonaire, Santo Eustáquio e Saba": "BQ",
    "Bósnia e Herzegovina": "BA",
    "Botsuana": "BW",
    "Ilha Bouvet": "BV",
    "Brasil": "BR",
    "Território Britânico do Oceano Índico": "IO",
    "Brunei": "BN",
    "Bulgária": "BG",
    "Burquina Faso": "BF",
    "Burundi": "BI",
    "Camboja": "KH",
    "Camarões": "CM",
    "Canadá": "CA",
    "Cabo Verde": "CV",
    "Ilhas Cayman": "KY",
    "República Centro-Africana": "CF",
    "Chade": "TD",
    "Chile": "CL",
    "China": "CN",
    "Ilha Christmas": "CX",
    "Ilhas Cocos (Keeling)": "CC",
    "Colômbia": "CO",
    "Comores": "KM",
    "Coreia do Sul": "KR",
    "Coreia do Norte": "KP",
    "Congo": "CG",
    "Congo (República Democrática do)": "CD",
    "Ilhas Cook": "CK",
    "Costa Rica": "CR",
    "Costa do Marfim": "CI",
    "Croácia": "HR",
    "Cuba": "CU",
    "Curaçao": "CW",
    "Chipre": "CY",
    "República Tcheca": "CZ",
    "Dinamarca": "DK",
    "Djibuti": "DJ",
    "Dominica": "DM",
    "República Dominicana": "DO",
    "Equador": "EC",
    "Egito": "EG",
    "El Salvador": "SV",
    "Guiné Equatorial": "GQ",
    "Eritreia": "ER",
    "Estônia": "EE",
    "Etiópia": "ET",
    "Ilhas Malvinas": "FK",
    "Ilhas Faroe": "FO",
    "Fiji": "FJ",
    "Finlândia": "FI",
    "França": "FR",
    "Guiana Francesa": "GF",
    "Polinésia Francesa": "PF",
    "Portugal": "PT",
    "Territórios Franceses do Sul": "TF",
    "Gabão": "GA",
    "Gâmbia": "GM",
    "Geórgia": "GE",
    "Alemanha": "DE",
    "Gana": "GH",
    "Gibraltar": "GI",
    "Grécia": "GR",
    "Groenlândia": "GL",
    "Granada": "GD",
    "Guadalupe": "GP",
    "Guam": "GU",
    "Guatemala": "GT",
    "Guernsey": "GG",
    "Guiné": "GN",
    "Guiné-Bissau": "GW",
    "Guiana": "GY",
    "Haiti": "HT",
    "Ilhas Heard e McDonald": "HM",
    "Vaticano": "VA",
    "Honduras": "HN",
    "Hong Kong": "HK",
    "Hungria": "HU",
    "Islândia": "IS",
    "Índia": "IN",
    "Indonésia": "ID",
    "Irã": "IR",
    "Iraque": "IQ",
    "Irlanda": "IE",
    "Ilha de Man": "IM",
    "Israel": "IL",
    "Itália": "IT",
    "Jamaica": "JM",
    "Japão": "JP",
    "Jersey": "JE",
    "Jordânia": "JO"
  };
  

